### ISSUE TITLE
add github fork-me sticker

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-angular-app#3]
Would be nice for users to see where they can fork this from/file issues/send merge requests etc.

**Comment by imaginator** [comment]
https://github.com/blog/273-github-ribbons

**Comment by robotnic** [comment]
Added small sticker

https://github.com/buddycloud/buddycloud-angular-app/commit/fbbc15bf15211afa806e5bfca40112ccdcbfb157
